parent=base
styles=css/lexstore.css

kcHtmlClass=lx-html
kcBodyClass=lx-body
kcLoginClass=lx-login
kcHeaderClass=lx-header
kcHeaderWrapperClass=lx-brand
kcFormCardClass=lx-card
kcFormHeaderClass=lx-card-header
kcContentWrapperClass=lx-content-wrapper
kcFormGroupClass=lx-group
kcLabelClass=lx-label
kcLabelWrapperClass=lx-label-wrap
kcInputClass=lx-input
kcInputWrapperClass=lx-input-wrap
kcInputGroup=lx-input-group
kcInputErrorMessageClass=lx-error
kcFormPasswordVisibilityButtonClass=lx-eye
kcFormPasswordVisibilityIconShow=lx-eye-show
kcFormPasswordVisibilityIconHide=lx-eye-hide
kcButtonClass=lx-btn
kcButtonPrimaryClass=lx-btn-primary
kcButtonDefaultClass=lx-btn-default
kcButtonBlockClass=lx-btn-block
kcButtonLargeClass=lx-btn-lg
kcAlertClass=lx-alert
kcAlertTitleClass=lx-alert-title
kcFormOptionsClass=lx-options
kcFormOptionsWrapperClass=lx-options-wrap
kcFormButtonsClass=lx-buttons
kcFormSettingClass=lx-setting
kcSignUpClass=lx-signup
kcInfoAreaWrapperClass=lx-info
kcLocaleMainClass=lx-locale
kcLocaleWrapperClass=lx-locale-wrap
kcLocaleDropDownClass=lx-locale-menu
kcLocaleListClass=lx-locale-list
kcLocaleListItemClass=lx-locale-item
kcLocaleItemClass=lx-locale-link
kcResetFlowIcon=lx-reset-icon
kcFeedbackErrorIcon=lx-feedback-error
kcFeedbackWarningIcon=lx-feedback-warning
kcFeedbackSuccessIcon=lx-feedback-success
kcFeedbackInfoIcon=lx-feedback-info
